service: serverless-lambda-sandbox
provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: dist/lambdas/hello.handler
    events:
      - http:
          path: hello
          method: GET
          cors: true
  double:
    handler: dist/lambdas/double.handler
    events:
      - http:
          path: double
          method: GET
          cors: true
